# Generated by Django 2.1.3 on 2018-12-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, default='')),
                ('result', models.NullBooleanField()),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('tracking', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('contract', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GithubAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, default='')),
                ('result', models.NullBooleanField()),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('tracking', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('repo', models.CharField(max_length=200)),
                ('contracts', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZipAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, default='')),
                ('result', models.NullBooleanField()),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('tracking', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('contracts', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
