# Generated by Django 2.1.3 on 2018-11-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contract', models.TextField()),
                ('report', models.TextField(blank=True, default='')),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Finished'), (2, 'Error'), (3, 'Expired'), (4, 'Performing'), (5, 'Queued')], default=5)),
            ],
        ),
    ]
