# Generated by Django 2.1.3 on 2018-12-03 05:27

import checkr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.TextField()),
                ('report', models.TextField(blank=True, default='')),
                ('result', models.NullBooleanField()),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('tracking', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=(checkr.models.TrackingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GithubAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=200)),
                ('files_directory', models.CharField(max_length=200)),
                ('report', models.TextField(blank=True, default='')),
                ('result', models.NullBooleanField()),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('tracking', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=(checkr.models.TrackingMixin, models.Model),
        ),
    ]
