# Generated by Django 2.1.3 on 2018-11-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='github_repo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='github_user',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='result',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='audit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
