# Generated by Django 2.1.3 on 2018-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkr', '0003_auto_20181124_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='tracking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
